name: Gate check
on: [push, pull_request]
jobs:
  python:
    if: platform == 'python'
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
          python-version: ${{ python-version }}
    - name: Run our test action
      uses: k8-proxy/s-k8-buildpipeline@python
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
  golang:
    if: platform == 'go'
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@master
    - name: Go Setup
      uses: actions/setup-go@v2
    - name: Run our test action
      uses: k8-proxy/s-k8-buildpipeline@go
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
